@baseUrl = https://localhost:7178
@scheduleId = 3

### AIRPORTS

### Get all active airports
GET {{baseUrl}}/api/airports
Accept: application/json


### SCHEDULES - GET

### Get all schedules
GET {{baseUrl}}/api/schedules
Accept: application/json


### Get schedule by ID
GET {{baseUrl}}/api/schedules/{{scheduleId}}
Accept: application/json


### Filter by origin
GET {{baseUrl}}/api/schedules?origin=1
Accept: application/json


### Filter by destination
GET {{baseUrl}}/api/schedules?destination=13
Accept: application/json


### Filter by status
GET {{baseUrl}}/api/schedules?status=Published
Accept: application/json


### Combined filters
GET {{baseUrl}}/api/schedules?origin=1&destination=13&status=Published
Accept: application/json

### CREATE SCHEDULE

POST {{baseUrl}}/api/schedules
Content-Type: application/json
Accept: application/json

{
  "flightNumber": "UL699",
  "originAirportId": 1,
  "destinationAirportId": 5,
  "departureTime": "10:30:00",
  "arrivalTime": "16:30:00",
  "aircraftType": "A330",
  "daysOfOperation": "1.3.5..",
  "effectiveFrom": "2026-11-01",
  "effectiveTo": "2027-03-31",
  "status": "Draft"
}


### UPDATE FULL SCHEDULE

PUT {{baseUrl}}/api/schedules/{{scheduleId}}
Content-Type: application/json
Accept: application/json

{
  "flightNumber": "UL455",
  "originAirportId": 1,
  "destinationAirportId": 9,
  "departureTime": "09:30:00",
  "arrivalTime": "11:30:00",
  "aircraftType": "A330",
  "daysOfOperation": "1...5.7",
  "effectiveFrom": "2026-08-21",
  "effectiveTo": "2026-10-23",
  "status": "Published"
}



### UPDATE STATUS ONLY

PATCH {{baseUrl}}/api/schedules/{{scheduleId}}/status
Content-Type: application/json
Accept: application/json

{
  "status": "Published"
}


### DELETE SCHEDULE

DELETE {{baseUrl}}/api/schedules/{{scheduleId}}
Accept: application/json